name: Lungisa
description: A project designed to assist leaders in fixing issues found in the community

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_form_builder: ^7.1.1
  form_builder_validators: ^8.1.1
  cupertino_icons: ^1.0.2
  camera: ^0.9.4+24
  path_provider: ^2.0.10
  path: ^1.8.1
  image_picker: ^0.8.5+3
  geolocator: ^5.3.1
  flutter_dotenv: ^5.0.2
  flutter_spinkit: ^5.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.0+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - variables.env
    - assets/app_icon.png
    - assets/lungisa_splashscreen.png

flutter_native_splash:
  image: assets/app_icon.png
  color: E79115
  android: true
  fullscreen: true
  android_gravity: fill
  ios_content_mode: scaleToFit